import AudioPlayer from './AudioPlayer';
import PlayPauseButton from './controls/PlayPauseButton';
import BackSkipButton from './controls/BackSkipButton';
import ForwardSkipButton from './controls/ForwardSkipButton';
import VolumeControl from './controls/VolumeControl';
import RepeatButton from './controls/RepeatButton';
import ShuffleButton from './controls/ShuffleButton';
import AudioProgress from './controls/AudioProgress';
import Spacer from './controls/Spacer';
import ProgressBar from './controls/common/ProgressBar';
import ProgressBarDisplay from './controls/common/ProgressBarDisplay';
import PurePropTypesComponent from './controls/common/PurePropTypesComponent';

module.exports = AudioPlayer;
module.exports.AudioPlayer = AudioPlayer;
module.exports.PlayPauseButton = PlayPauseButton;
module.exports.BackSkipButton = BackSkipButton;
module.exports.ForwardSkipButton = ForwardSkipButton;
module.exports.VolumeControl = VolumeControl;
module.exports.RepeatButton = RepeatButton;
module.exports.ShuffleButton = ShuffleButton;
module.exports.AudioProgress = AudioProgress;
module.exports.Spacer = Spacer;
module.exports.ProgressBar = ProgressBar;
module.exports.ProgressBarDisplay = ProgressBarDisplay;
module.exports.PurePropTypesComponent = PurePropTypesComponent;
